/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/games/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get best games */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get best games */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BestGame"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/best/{userEmail}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get best 10 games of a user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userEmail: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get best 10 games of a user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Game"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{userEmail}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get last 10 games of a user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userEmail: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get last 10 games of a user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Game"][];
                    };
                };
                /** @description user not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            responses: {
                /** @description Create a game */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsAll"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/user/{userEmail}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get stats of a user (from cache) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userEmail: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get stats of a user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Stats"];
                    };
                };
                /** @description Stats not found for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get user profile by userId */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get user profile by userId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get stats of a user by userId (from cache) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get stats of a user by userId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserStats"];
                    };
                };
                /** @description User or stats not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/games/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get last 10 games of a user by userId */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get last 10 games of a user by userId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserGame"][];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/games/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get best 10 games of a user by userId */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get best 10 games of a user by userId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserGame"][];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skins/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all skin types */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkinTypesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skins/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all skins */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            default?: number;
                            flowerfloor?: number;
                            "inferno-hard"?: number;
                            igloo?: number;
                            "jade-temple"?: number;
                            "paper-cutout"?: number;
                            "void-orchid"?: number;
                            "minimal-zoned"?: number;
                            antic?: number;
                            "emoji-tiles"?: number;
                            "heart-tiles"?: number;
                            "laughing-faces"?: number;
                            "fruit-basket"?: number;
                            "red-burst"?: number;
                            "orange-pop"?: number;
                            "yellow-zest"?: number;
                            "green-garden"?: number;
                            "blue-lagoon"?: number;
                            "purple-parade"?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skins/banners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all banners */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all banners */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            default?: number;
                            level?: number;
                            gold?: number;
                        };
                    };
                };
                /** @description Banners not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skins/backgrounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all backgrounds */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all backgrounds */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            default?: number;
                            "flower-floor"?: number;
                            igloo?: number;
                            "aurora-drift"?: number;
                            "retro-grid"?: number;
                            "amber-dunes"?: number;
                            "deep-reef"?: number;
                        };
                    };
                };
                /** @description Backgrounds not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skins/user/{userEmail}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get skins of a user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userEmail: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get skins of a user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSkins"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skins/buy/{userEmail}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userEmail: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        skinType: "cells";
                        skin: components["schemas"]["CellSkinsNamesEnum"];
                    } | {
                        /** @enum {string} */
                        skinType: "banner";
                        /** @enum {string} */
                        skin: "default" | "level" | "gold";
                    } | {
                        /** @enum {string} */
                        skinType: "background";
                        skin: components["schemas"]["BackgroundSkinsNamesEnum"];
                    };
                };
            };
            responses: {
                /** @description Buy a skin */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Not enough coins */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skins/select/{userEmail}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userEmail: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        skinType: "cells";
                        skin: components["schemas"]["CellSkinsNamesEnum"];
                    } | {
                        /** @enum {string} */
                        skinType: "banner";
                        /** @enum {string} */
                        skin: "default" | "level" | "gold";
                    } | {
                        /** @enum {string} */
                        skinType: "background";
                        skin: components["schemas"]["BackgroundSkinsNamesEnum"];
                    };
                };
            };
            responses: {
                /** @description Select a skin */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Skin not unlocked */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BestGame: {
            userId: string;
            time: number;
            flags: number;
            date: string;
            userName: string;
            userPicture: string;
        };
        Game: {
            /** @enum {string} */
            status: "won" | "lost" | "restarted";
            time: number;
            flags: number;
            revealed: number;
            date: string;
            userEmail: string;
            userName: string;
            userPicture: string;
        };
        StatsAll: {
            totalGames: number;
            totalTime: number;
            totalFlags: number;
            totalRevealed: number;
            totalBombs: number;
            totalWin: number;
            bestTime?: number;
            totalNoFlagsWin: number;
            totalRestarts: number;
            userPicture: string;
            userName: string;
            userId: string;
        };
        Stats: {
            totalGames: number;
            totalTime: number;
            totalFlags: number;
            totalRevealed: number;
            totalBombs: number;
            totalWin: number;
            bestTime?: number;
            totalNoFlagsWin: number;
            totalRestarts: number;
        };
        User: {
            userId: string;
            userName: string;
            userPicture: string;
        };
        UserStats: {
            totalGames: number;
            totalTime: number;
            totalFlags: number;
            totalRevealed: number;
            totalBombs: number;
            totalWin: number;
            bestTime?: number;
            totalNoFlagsWin: number;
            totalRestarts: number;
        };
        UserGame: {
            /** @enum {string} */
            status: "won" | "lost" | "restarted";
            time: number;
            flags: number;
            revealed: number;
            date: string;
            userName: string;
            userPicture: string;
        };
        SkinTypesResponse: components["schemas"]["SkinType"][];
        /** @enum {string} */
        SkinType: "cells" | "banner" | "background";
        UserSkins: {
            userId: string;
            userName: string;
            userPicture: string;
            coins: number;
            selectedSkin?: {
                cells?: components["schemas"]["CellSkin"];
                banner?: components["schemas"]["BannerSkin"];
                background?: components["schemas"]["BackgroundSkin"];
            };
            unlockedSkins?: {
                cells?: components["schemas"]["CellSkin"][];
                banner?: components["schemas"]["BannerSkin"][];
                background?: components["schemas"]["BackgroundSkin"][];
            };
        };
        /** @enum {string} */
        CellSkin: "default" | "flowerfloor" | "inferno-hard" | "igloo" | "jade-temple" | "paper-cutout" | "void-orchid" | "minimal-zoned" | "antic" | "emoji-tiles" | "heart-tiles" | "laughing-faces" | "fruit-basket" | "red-burst" | "orange-pop" | "yellow-zest" | "green-garden" | "blue-lagoon" | "purple-parade";
        /** @enum {string} */
        BannerSkin: "default" | "level" | "gold";
        /** @enum {string} */
        BackgroundSkin: "default" | "flower-floor" | "igloo" | "aurora-drift" | "retro-grid" | "amber-dunes" | "deep-reef";
        /** @enum {string} */
        CellSkinsNamesEnum: "default" | "flowerfloor" | "inferno-hard" | "igloo" | "jade-temple" | "paper-cutout" | "void-orchid" | "minimal-zoned" | "antic" | "emoji-tiles" | "heart-tiles" | "laughing-faces" | "fruit-basket" | "red-burst" | "orange-pop" | "yellow-zest" | "green-garden" | "blue-lagoon" | "purple-parade";
        /** @enum {string} */
        BackgroundSkinsNamesEnum: "default" | "flower-floor" | "igloo" | "aurora-drift" | "retro-grid" | "amber-dunes" | "deep-reef";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
